FROM centos:7
RUN yum -y update \
    && yum -y install epel-release\
    && yum -y install python-pip\
    && yum clean all
RUN pip install prometheus_client requests pyyaml
COPY version/VERSION /exporter/
COPY exporter.py /exporter/
COPY metrics.json /exporter/
RUN touch /exporter/exporter.log
RUN ln -sf /dev/stdout /exporter/exporter.log


ENTRYPOINT ["python", "/exporter/exporter.py" ]
